### ISSUE TITLE
NuGet Error

### ISSUE THREAD

**Issue by VBAndCs** [mikadumont/BlazorMemoryGame#8]
Hi @mikadumont 
When restoring NuGets, I get this error:
> Error occurred while restoring NuGet packages: Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json.

The full error message:
> C:\Program Files\dotnet\sdk\5.0.300\NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json. [E:\Github\BlazorMemoryGame-main\BlazorMemoryGame.sln]
C:\Program Files\dotnet\sdk\5.0.300\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [E:\Github\BlazorMemoryGame-main\BlazorMemoryGame.sln]
C:\Program Files\dotnet\sdk\5.0.300\NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [E:\Github\BlazorMemoryGame-main\BlazorMemoryGame.sln]

Thanks.

**Comment by VBAndCs** [comment]
I found the cause of the error:
The url https://dotnet.myget.org/F/roslyn/api/v3/index.json is wrong, and the working one doesn't have the `dotnet.` prefix :
https://myget.org/F/roslyn/api/v3/index.json
But where/how I can change this url in the app. I don't see it in the project file.

**Comment by mikadumont** [comment]
Hi @VBAndCs this issue is happening because you have myget set in your Visual Studio settings. If you go to Tools -> Options -> Nuget Package Manager -> Package Source you should see this entry listed. You need to remove it.
![image](https://user-images.githubusercontent.com/46729679/121101845-79b55d80-c7b1-11eb-8ec2-aec1bd788f93.png)

**Comment by VBAndCs** [comment]
Thanks @mikadumont. This was helpful.
In fact, I removed the one shown:
![untitled1](https://user-images.githubusercontent.com/48354902/121122052-077c6180-c821-11eb-98da-dafa50007fe1.jpg)
Another option, is to let it selected, but use text boxes at the bottom of the screen to modify its URL.
Both worked for me.
The project builds and runs perfectly, but still there is an error in the test project, as there is no Create method in the generated class:
![untitled2](https://user-images.githubusercontent.com/48354902/121123548-b457de00-c823-11eb-82bd-6ef89968a5a2.jpg)

Thanks.
